In [1]:
import numpy as np

In [2]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

In [4]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [5]:
c1 = a_centered[:5,0:1].copy()
c1

array([[-1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [-1.]])

In [6]:
c2 = a_centered[:5,1:].copy()
c2

array([[-2.4],
       [-0.4],
       [ 2.6],
       [ 1.6],
       [-1.4]])

In [7]:
c1 = c1.flatten()
c1

array([-1.,  0.,  1.,  1., -1.])

In [8]:
c2 = c2.flatten()
c2

array([-2.4, -0.4,  2.6,  1.6, -1.4])

In [9]:
a_centered_sp = c1.dot(c2)
a_centered_sp

8.0

In [10]:
result = a_centered_sp/(a.size - 1)
result

0.8888888888888888